@startuml

!include style.puml

Actor User as user USER_COLOR
Participant ":Logic" as logic LOGIC_COLOR
Participant ":Model" as model MODEL_COLOR
Participant ":Storage" as storage STORAGE_COLOR
Participant ":Ui" as Ui UI_COLOR

note left of user: The user is in limit mode

user -[USER_COLOR]> logic : "set budget 10 daily"
activate logic LOGIC_COLOR

logic -[LOGIC_COLOR]> logic : verifySetCommand()
activate logic LOGIC_COLOR_T1
deactivate logic

logic -[LOGIC_COLOR]> logic : AddLimitCommand(budget, 10, daily)
activate logic LOGIC_COLOR_T1
deactivate logic

logic -[LOGIC_COLOR]> model : addToRecordList(mode, newLimit)
activate model MODEL_COLOR

model -[LOGIC_COLOR]> storage : setLimits(get())
activate storage STORAGE_COLOR

storage -[STORAGE_COLOR]> storage : save to file
activate storage STORAGE_COLOR_T1
deactivate storage

storage --[STORAGE_COLOR]> model
deactivate storage

model --[MODEL_COLOR]> logic
deactivate model

logic -[UI_COLOR]> Ui : echoAddLimit(newLimit)
activate Ui UI_COLOR

Ui--[UI_COLOR]> logic
deactivate Ui

logic --[LOGIC_COLOR]> user
deactivate logic
@enduml