@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

package Logic {
Class HiddenLogic #FFFFFF
}

Package Ui <<Rectangle>> {

Class XYZUi
Class "{abstract}\nUi" as Ui
note right of XYZUi: XYZUi = EntryUi, \nDebtUi, LimitUi etc

XYZUi --|>Ui
HiddenLogic ..> XYZUi : calls >

}

@enduml